### ISSUE TITLE
Won't correctly parse array with multiple dependencies

### ISSUE THREAD

**Issue by giantsoup** [mattiLeBlanc/gulp-wp-bump-all#1]
I love this package and I really want to use it but it is currently not able to parse a dependency array that has multiple dependencies. I have a wp_enqueue_script that end with this:

`array( 'jquery', 'plugins' ),'1.0.0', true );`

Because it has the second dependency 'plugins' the result of the script ends up being this:

`array( 'jquery','09db156ac6ab55','1.0.0', true );`

Which is invalid. It should look like this after that bump occurs:

`array( 'jquery', 'plugins' ), '09db156ac6ab55', true );`

i have another wp_enqueue_script that only has a dependency of 'jquery', and that is working beautifully.

I'm really hoping you can alter whatever process is parsing the functions.php file to handle more than one dependency, because this automatic bump would save me so much time. Other than this issue its an amazing little package, thank you for writing it.

**Comment by mattiLeBlanc** [comment]
@giantsoup Good feedback! I haven't tested it for different scenario's so thanks for that.
I will make the required adjustments so you can move on with your project. 
No worries! Should be done today.

**Comment by mattiLeBlanc** [comment]
Issue has been tested and resolved. Version 0.3.0 available in NPM.

**Comment by giantsoup** [comment]
Just downloaded new version and works great! 👍 

Thanks so much for the update.
